package com.example.examplemod;

public enum GameStateEnum {
	DISABLED,
	ONSERVER,
	HUB,
	AUCTIONHOUSE,
	CONTINUEFIRSTWINDOW,
	EXITFIRSTWINDOW,
	COMMANDREADY,
	COMMANDSENT,
	SECONDWINDOW,
	CONTINUESECONDWINDOW,
}
